In [1]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
a=np.random.randint(1,20,4)   #here 1,10 is the range means give me 4 numbers having values between 1-20
a

array([11, 15, 14,  8])

In [3]:
b=np.random.randint(1,100,10).reshape(5,2) #HERE  it will give 5Rows and 2Coluns 
b

array([[71, 36],
       [67, 15],
       [80, 14],
       [31, 46],
       [44, 37]])

In [4]:
c= np.random.randint(10,size=(2,5))  #Here we gives range upto 10 with dim 2,3
c

array([[5, 8, 5, 5, 3],
       [8, 4, 3, 3, 8]])

In [5]:
c =np.random.rand(10)
c

array([0.02919012, 0.38602547, 0.28261849, 0.03190032, 0.70344315,
       0.12131771, 0.69307522, 0.91701161, 0.60776708, 0.8860532 ])

In [6]:
e=np.zeros((3,4))
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
#Converting Array to Python List
f=e.tolist()
f

[[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]

In [8]:
np.info(np.ones)

 ones(shape, dtype=None, order='C', *, like=None)

Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and order.

See Also
--------
o

In [9]:
np.info(np.arange(5))

class:  ndarray
shape:  (5,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x5b6cb479a1e0
byteorder:  little
byteswap:  False
type: int64


In [10]:
g=np.random.randint(1,100,5)
g

array([37,  3, 58, 95, 81])

In [11]:
h=np.sort(g)
h

array([ 3, 37, 58, 81, 95])

In [12]:
#here we will  a eye matrix
i=np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
j=np.random.randint(1,100,12).reshape(3,4)
print(j)
print(j.T)  #The Trans (T)  will (row  becomes columns vice versa)

[[76 34 63 37]
 [15 85 92 85]
 [85 13 74 74]]
[[76 15 85]
 [34 85 13]
 [63 92 74]
 [37 85 74]]


In [14]:
np.save('Numpy',j)
#it will stores in '/kaggle/workin/'

In [15]:
np.load('Numpy.npy')

array([[76, 34, 63, 37],
       [15, 85, 92, 85],
       [85, 13, 74, 74]])

In [16]:
import numpy as np
k=np.arange(2,1000,1)
print(k)
print("size is :",np.size(k))

[  2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163
 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181
 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199
 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235
 236 237 238 239 240 241 242 243 244 245 246 247 24

In [17]:
#While Reshapeing the numpy array  dimension must be multyply of total elements 
import numpy as np

In [18]:
l = np.arange(1,13,1)
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
#Reshape the  above array to 2 dimension
m =l.reshape(3,4)
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
m.ndim

2

In [21]:
#To  convert the multy dimensional  arary to 1-D  array
print(m)
n =m.reshape(-1)    # -1 will converty it to 1 -D array 
n


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
for x in n:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [23]:
o = np.arange(1,13,1,dtype=int).reshape(4,3,-1)
o
# for y in np.nditer(o):
#     print(y)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [24]:
import numpy as np
arr =np.array([1,2,3])
arr1 =np.array([4,5,6])
hfinal =np.hstack((arr ,arr1)) #will add  the array in hor
vfinal =np.vstack((arr,arr1)) #will add  the array in ver

print(hfinal)
print(vfinal)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [25]:
p =np.array([1,2,3])
p1=np.array([4,5,6])
p22 =np.dstack((p,p1)) 
p22

array([[[1, 4],
        [2, 5],
        [3, 6]]])